#!/system/bin/sh

#Memory optimize
swapoff /dev/block/zram0
echo 1 >/sys/block/zram0/reset
echo 4G >/sys/block/zram0/disksize
echo 4096M > /sys/block/zram0/mem_limit
mkswap /dev/block/zram0
swapon /dev/block/zram0

echo 80 > /proc/sys/vm/swappiness
echo 80 > /proc/sys/vm/vfs_cache_pressure
echo 0 > /proc/sys/vm/page-cluster
echo 10 > /proc/sys/vm/dirty_ratio
echo 0 > /proc/sys/vm/watermark_boost_factor
echo 32 > /proc/sys/vm/watermark_scale_factor
echo 20 > /proc/sys/vm/stat_interval
echo 400 > /proc/sys/vm/dirty_expire_centisecs
echo 3000 > /proc/sys/vm/dirty_writeback_centisecs
echo 750 > /proc/sys/vm/extfrag_threshold
echo 1 > /proc/sys/vm/overcommit_memory
echo 50 > /proc/sys/vm/overcommit_ratio
echo 1 > /proc/sys/vm/compact_unevictable_allowed
echo 1 > /proc/sys/vm/compact_memory
sleep 20
echo 3 > /proc/sys/vm/drop_caches
